version: '3.8'

services:
    laravel_apache:
        build: ./

        networks:
            - network1
    
    nginx_reverse_proxy:
        build:
            context: ./
            dockerfile: Dockerfile.nginx
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - 127.0.0.1:8081:80
        depends_on:
            - laravel_apache
        
        networks:
            - network1
        

networks:
    network1:

#Thanks to
#https://medium.com/@prasunamudawari/set-up-a-laravel-application-with-nginx-and-mysql-with-docker-compose-58771e535a28
#https://dev.to/adnanbabakan/dockerizing-laravel-10-ubuntu-image-php-82-fpm-nginx-318p